### ISSUE TITLE
GitHub token creation/nbinit

### ISSUE THREAD

**Issue by betatim** [earthlab/abc-classroom#14]
When running `nbinit` check local`config.yaml` for existing token and reuse it.

If there is no token then use something unique in the note for creating the token as we can't create two tokens with the same name.

**Comment by betatim** [comment]
Alternatively place the token in `~/.abc.config` and share it between all courses.

**Comment by lwasser** [comment]
Note - this is the error i get running `nbinit` when i already have a token (just for the record)
```
Traceback (most recent call last):
  File "/Users/leah-su/anaconda3/bin/nbinit", line 11, in <module>
    sys.exit(init())
  File "/Users/leah-su/anaconda3/lib/python3.6/site-packages/grading/__main__.py", line 60, in init
    two_factor_callback=two_factor)
  File "/Users/leah-su/anaconda3/lib/python3.6/site-packages/github3/api.py", line 26, in deprecation_wrapper
    return func(*args, **kwargs)
  File "/Users/leah-su/anaconda3/lib/python3.6/site-packages/github3/api.py", line 59, in authorize
    client_secret)
  File "/Users/leah-su/anaconda3/lib/python3.6/site-packages/github3/github.py", line 462, in authorize
    json = self._json(self._post(url, data=data), 201)
  File "/Users/leah-su/anaconda3/lib/python3.6/site-packages/github3/models.py", line 156, in _json
    raise exceptions.error_for(response)
github3.exceptions.UnprocessableEntity: 422 Validation Failed
```

**Comment by lwasser** [comment]
related to this is -- is this `authorize()` call deprecated? [see here please](https://github.com/sigmavirus24/github3.py/blob/master/src/github3/api.py#L34). something odd is going on with the init command that i can't figure out .i seem to have to delete it each time or every so often. could be user error!

**Comment by betatim** [comment]
Good catch with the deprecation. I hadn't noticed this. Take a look at #40

**Comment by betatim** [comment]
#40 doesn't quite close this issue as we still use a file local to the repository to store the token instead of placing it in `~/.abc.token` (or some such). That is for another PR to solve.
