### ISSUE TITLE
Unexpected result of running abc-feedback twice (first without --github and then with --github)

### ISSUE THREAD

**Issue by jlpalomino** [earthlab/abc-classroom#181]
I will add more here (including the full error message) after I test this again with assignment 5, but below is the basic situation.

For assignment 2, I ran `abc-feedback` without `--github` and then realized that I left out that option. So I ran `abc-feedback` again with `--github` and got a message that there were already commits ready to push but it did not push without me manually typing `git push` for each repository.

**Comment by jlpalomino** [comment]
OK @kcranston  I happened to do it again accidentally, so I am able to provide the message and workaround now.

I ran `abc-feedback ea-python-2020-05-what-the-fork-who-did-this` the first time without `--github` (on accident).  So then, I ran the same command again with `--github` and got this message:

```
(earth-analytics-python) jpalomino@earthlab-P50:~/git/repos/earth-analytics-edu/master-branch/2020-ea-python-course$ abc-feedback ea-python-2020-05-what-the-fork-who-did-this --github
Loading configuration from config.yml
copying /home/jpalomino/git/repos/earth-analytics-edu/master-branch/2020-ea-python-course/spring-2020-eapython-nbgrader/feedback/annapav7/ea-python-2020-05-what-the-fork-who-did-this/colored-bar.png to cloned_dirs/ea-python-2020-05-what-the-fork-who-did-this-annapav7
copying /home/jpalomino/git/repos/earth-analytics-edu/master-branch/2020-ea-python-course/spring-2020-eapython-nbgrader/feedback/annapav7/ea-python-2020-05-what-the-fork-who-did-this/ea-python-2020-05-what-the-fork-who-did-this.html to cloned_dirs/ea-python-2020-05-what-the-fork-who-did-this-annapav7
copying /home/jpalomino/git/repos/earth-analytics-edu/master-branch/2020-ea-python-course/spring-2020-eapython-nbgrader/feedback/annapav7/ea-python-2020-05-what-the-fork-who-did-this/earth-lab-logo-rgb.png to cloned_dirs/ea-python-2020-05-what-the-fork-who-did-this-annapav7
Traceback (most recent call last):
  File "/home/jpalomino/miniconda3/envs/earth-analytics-python/lib/python3.7/site-packages/abcclassroom/github.py", line 27, in _call_git
    stderr=subprocess.PIPE,
  File "/home/jpalomino/miniconda3/envs/earth-analytics-python/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'commit', '-a', '-m', 'Adding feedback for assignment ea-python-2020-05-what-the-fork-who-did-this']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jpalomino/miniconda3/envs/earth-analytics-python/bin/abc-feedback", line 8, in <module>
    sys.exit(feedback())
  File "/home/jpalomino/miniconda3/envs/earth-analytics-python/lib/python3.7/site-packages/abcclassroom/__main__.py", line 148, in feedback
    fdback.copy_feedback(args)
  File "/home/jpalomino/miniconda3/envs/earth-analytics-python/lib/python3.7/site-packages/abcclassroom/feedback.py", line 56, in copy_feedback
    msg="Adding feedback for assignment {}".format(assignment),
  File "/home/jpalomino/miniconda3/envs/earth-analytics-python/lib/python3.7/site-packages/abcclassroom/github.py", line 151, in commit_all_changes
    _call_git("commit", "-a", "-m", msg, directory=directory)
  File "/home/jpalomino/miniconda3/envs/earth-analytics-python/lib/python3.7/site-packages/abcclassroom/github.py", line 33, in _call_git
    raise RuntimeError(err) from e
RuntimeError: On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)
nothing to commit, working directory clean
```

To get the file to push to GitHub, I had to go into each cloned directory and run `git push origin master`.

**Comment by kcranston** [comment]
Thanks, @jlpalomino 
What version of abc-classroom are you using (installed from github or from pip)?

**Comment by jlpalomino** [comment]
I believe I installed using pip, and it looks like I am slightly behind in version.  Here is what I see under ```conda list```:

```abc-classroom             0.0.13                   pypi_0    pypi```

**Comment by lwasser** [comment]
@jlpalomino we bumped to version .14 a week or two ago (feb 6).
https://pypi.org/project/abc-classroom/ 
so you should probably update as there are a bunch of breaking fixes!  but karen can tell you about non released breaking fixes. i've been running locally by pulling from master and installing interactively. 

`pip install -e .`

**Comment by jlpalomino** [comment]
@lwasser I will update my version to 0.0.14 using pip and report back after I grade the next assignment next week.

**Comment by jlpalomino** [comment]
OK @kcranston @lwasser Finally testing this issue again after updating abc-classroom to version to 0.0.14 using pip, and I am getting the same error. 

I ran abc-feedback ea-python-2020-07-ndvi-automation the first time without --github. So then, I ran the same command again with --github and got the same message about needing to git push, which I have to do in each cloned student repo individually:

```
(earth-analytics-python) jpalomino@earthlab-P50:~/git/repos/earth-analytics-edu/master-branch/2020-ea-python-course$ abc-feedback ea-python-2020-07-ndvi-automation --github

Loading configuration from config.yml
copying /home/jpalomino/git/repos/earth-analytics-edu/master-branch/2020-ea-python-course/spring-2020-eapython-nbgrader/feedback/annapav7/ea-python-2020-07-ndvi-automation/colored-bar.png to cloned_dirs/ea-python-2020-07-ndvi-automation-annapav7
copying /home/jpalomino/git/repos/earth-analytics-edu/master-branch/2020-ea-python-course/spring-2020-eapython-nbgrader/feedback/annapav7/ea-python-2020-07-ndvi-automation/ea-python-2020-07-ndvi-automation.html to cloned_dirs/ea-python-2020-07-ndvi-automation-annapav7
copying /home/jpalomino/git/repos/earth-analytics-edu/master-branch/2020-ea-python-course/spring-2020-eapython-nbgrader/feedback/annapav7/ea-python-2020-07-ndvi-automation/earth-lab-logo-rgb.png to cloned_dirs/ea-python-2020-07-ndvi-automation-annapav7
Traceback (most recent call last):
  File "/home/jpalomino/miniconda3/envs/earth-analytics-python/lib/python3.7/site-packages/abcclassroom/github.py", line 27, in _call_git
    stderr=subprocess.PIPE,
  File "/home/jpalomino/miniconda3/envs/earth-analytics-python/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'commit', '-a', '-m', 'Adding feedback for assignment ea-python-2020-07-ndvi-automation']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jpalomino/miniconda3/envs/earth-analytics-python/bin/abc-feedback", line 8, in <module>
    sys.exit(feedback())
  File "/home/jpalomino/miniconda3/envs/earth-analytics-python/lib/python3.7/site-packages/abcclassroom/__main__.py", line 148, in feedback
    fdback.copy_feedback(args)
  File "/home/jpalomino/miniconda3/envs/earth-analytics-python/lib/python3.7/site-packages/abcclassroom/feedback.py", line 56, in copy_feedback
    msg="Adding feedback for assignment {}".format(assignment),
  File "/home/jpalomino/miniconda3/envs/earth-analytics-python/lib/python3.7/site-packages/abcclassroom/github.py", line 151, in commit_all_changes
    _call_git("commit", "-a", "-m", msg, directory=directory)
  File "/home/jpalomino/miniconda3/envs/earth-analytics-python/lib/python3.7/site-packages/abcclassroom/github.py", line 33, in _call_git
    raise RuntimeError(err) from e
RuntimeError: On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)
nothing to commit, working directory clean
```

**Comment by kcranston** [comment]
Looks like we need a new release. The 0.0.14 release is dated Feb 6, and the [pull request](https://github.com/earthlab/abc-classroom/pull/171) that (should) fix this was merged March 5.

**Comment by lwasser** [comment]
@jlpalomino i can push a new release this week. but can you just install locally from master and see if your issues are resolved first? If they are I'll push a release!

**Comment by jlpalomino** [comment]
@lwasser  This issue is resolved!  I installed abc-classroom locally from master and tested `abc-feedback` without `--github` and then again with `-- github`.  The feedback was successfully sent back to eastudent's repository when I used `--github` the second time I ran the command.

**Comment by lwasser** [comment]
yay!! ok thank you @jlpalomino i'll go ahead and plan to release a new version this week
if you can hang tight and just work locally on rather than from the pip version for a day or two that would be great!!  i'll close this now but reopen if you encounter other issues!
