### ISSUE TITLE
Modify to friendlier message after running `abc-feedback --github` after no new feedback report is generated

### ISSUE THREAD

**Issue by jlpalomino** [earthlab/abc-classroom#182]
For assignment 2 for which feedback has already been released, I get a long error message after running `abc-feedback --github`, and then I finally see that there is nothing new to commit, which makes sense.

The message should be condensed for the user, so that it is clear that there is actually no problem here. 

```
Loading configuration from config.yml
copying /home/jpalomino/git/repos/earth-analytics-edu/master-branch/2020-ea-python-course/spring-2020-eapython-nbgrader/feedback/annapav7/ea-python-2020-02-lidar-raster/colored-bar.png to cloned_dirs/ea-python-2020-02-lidar-raster-annapav7
copying /home/jpalomino/git/repos/earth-analytics-edu/master-branch/2020-ea-python-course/spring-2020-eapython-nbgrader/feedback/annapav7/ea-python-2020-02-lidar-raster/ea-python-2020-02-lidar-raster-hw.html to cloned_dirs/ea-python-2020-02-lidar-raster-annapav7
copying /home/jpalomino/git/repos/earth-analytics-edu/master-branch/2020-ea-python-course/spring-2020-eapython-nbgrader/feedback/annapav7/ea-python-2020-02-lidar-raster/earth-lab-logo-rgb.png to cloned_dirs/ea-python-2020-02-lidar-raster-annapav7
Traceback (most recent call last):
  File "/home/jpalomino/miniconda3/envs/earth-analytics-python/lib/python3.7/site-packages/abcclassroom/github.py", line 27, in _call_git
    stderr=subprocess.PIPE,
  File "/home/jpalomino/miniconda3/envs/earth-analytics-python/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'commit', '-a', '-m', 'Adding feedback for assignment ea-python-2020-02-lidar-raster']' returned non-zero exit status 1.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/jpalomino/miniconda3/envs/earth-analytics-python/bin/abc-feedback", line 8, in <module>
    sys.exit(feedback())
  File "/home/jpalomino/miniconda3/envs/earth-analytics-python/lib/python3.7/site-packages/abcclassroom/__main__.py", line 148, in feedback
    fdback.copy_feedback(args)
  File "/home/jpalomino/miniconda3/envs/earth-analytics-python/lib/python3.7/site-packages/abcclassroom/feedback.py", line 56, in copy_feedback
    msg="Adding feedback for assignment {}".format(assignment),
  File "/home/jpalomino/miniconda3/envs/earth-analytics-python/lib/python3.7/site-packages/abcclassroom/github.py", line 151, in commit_all_changes
    _call_git("commit", "-a", "-m", msg, directory=directory)
  File "/home/jpalomino/miniconda3/envs/earth-analytics-python/lib/python3.7/site-packages/abcclassroom/github.py", line 33, in _call_git
    raise RuntimeError(err) from e
RuntimeError: On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
```

**Comment by lwasser** [comment]
@kcranston i see you referenced this issue in a old PR that was merged. Can we close it? i'm doing some cleanup . please close IF we can close!

**Comment by lwasser** [comment]
yes!
