### ISSUE TITLE
still getting file exists error

### ISSUE THREAD

**Issue by lwasser** [earthlab/abc-classroom#187]
i have tried to delete the repo dir and it's still not working and the error is really not helpful.
```
Loading configuration from config.yml
Creating new template repo at assignment-template-repos/ea-python-2020-06-multispectral-remote-sensing-template
Getting assignment files
Traceback (most recent call last):
  File "/Users/leahwasser/miniconda3/envs/earth-analytics-python/bin/abc-new-template", line 11, in <module>
    load_entry_point('abc-classroom', 'console_scripts', 'abc-new-template')()
  File "/Users/leahwasser/Documents/github/0-python/abc-classroom/abcclassroom/__main__.py", line 181, in new_template
    template.new_update_template(args)
  File "/Users/leahwasser/Documents/github/0-python/abc-classroom/abcclassroom/template.py", line 30, in new_update_template
    copy_assignment_files(config, template_repo_path, assignment)
  File "/Users/leahwasser/Documents/github/0-python/abc-classroom/abcclassroom/template.py", line 184, in copy_assignment_files
    shutil.copytree(item, template_repo)
  File "/Users/leahwasser/miniconda3/envs/earth-analytics-python/lib/python3.7/shutil.py", line 324, in copytree
    os.makedirs(dst)
  File "/Users/leahwasser/miniconda3/envs/earth-analytics-python/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/Users/leahwasser/Documents/github/1-courses/0-professional-certificate/2020-ea-python-course/assignment-template-repos/ea-python-2020-06-multispectral-remote-sensing-template'
(earth-analytics-python) CIRES-EL-LM-020:2020-ea-python-course leahwasser$ 
```

**Comment by lwasser** [comment]
i left a really bad message here and i haven't seen this issue in a while so i'll close this for now.
