### ISSUE TITLE
nbdistribute -- fails when student repo doesn't exist

### ISSUE THREAD

**Issue by lwasser** [earthlab/abc-classroom#37]
previous there was an issue with nbdistribute that i thought i'd fixed with a pr -- but now i'm getting another error here - it's returning the appropriate message but still trying to clone their repo. 
```
Fetching work for jlpalomino...
Student jlpalomino does not have a repository for this course, maybe they have not accepted the invitation yet? Skipping them for now.
Traceback (most recent call last):
  File "/Users/leah-su/anaconda3/envs/earth-analytics-python/bin/nbdistribute", line 11, in <module>
    load_entry_point('grading', 'console_scripts', 'nbdistribute')()
  File "/Users/leah-su/Documents/github/2-autograding/grading-workflow-experiments/grading/__main__.py", line 253, in distribute
    token=config['github']['token'])
  File "/Users/leah-su/Documents/github/2-autograding/grading-workflow-experiments/grading/github.py", line 68, in fetch_student
    stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/Users/leah-su/anaconda3/envs/earth-analytics-python/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'clone', 'https://5818fe6a99b8b11d832e3da6d6f8098640fc639f@github.com/earth-analytics-edu/ea-spring-2019-jlpalomino.git']' returned non-zero exit status 128.
```

**Comment by betatim** [comment]
I can't reproduce this with the code as of 444a205915586edeed35bab6b2a1bba2ce5df27f :-/

**Comment by lwasser** [comment]
ok let me try to update and will test this again! 
thank you @betatim

**Comment by lwasser** [comment]
closing this for the time being ...  it's dated
