### ISSUE TITLE
Docs are failing

### ISSUE THREAD

**Issue by lwasser** [earthlab/abc-classroom#414]
Not sure what is  triggering this but it started 3 weeks ago. will need to build locally to see what is going on .

```

generating indices... genindex failed

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/abc-classroom/envs/latest/lib/python3.7/site-packages/sphinx/builders/html/__init__.py", line 1044, in handle_page
    output = self.templates.render(templatename, ctx)
  File "/home/docs/checkouts/readthedocs.org/user_builds/abc-classroom/envs/latest/lib/python3.7/site-packages/readthedocs_ext/readthedocs.py", line 185, in rtd_render
    content = old_render(template, render_context)
  File "/home/docs/checkouts/readthedocs.org/user_builds/abc-classroom/envs/latest/lib/python3.7/site-packages/sphinx/jinja2glue.py", line 191, in render
    return self.environment.get_template(template).render(context)
  File "/home/docs/checkouts/readthedocs.org/user_builds/abc-classroom/envs/latest/lib/python3.7/site-packages/jinja2/environment.py", line 1289, in render
    self.environment.handle_exception()
  File "/home/docs/checkouts/readthedocs.org/user_builds/abc-classroom/envs/latest/lib/python3.7/site-packages/jinja2/environment.py", line 924, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/docs/checkouts/readthedocs.org/user_builds/abc-classroom/envs/latest/lib/python3.7/site-packages/sphinx/themes/basic/genindex.html", line 28, in top-level template code
    {{ firstname|e }}
  File "/home/docs/checkouts/readthedocs.org/user_builds/abc-classroom/envs/latest/lib/python3.7/site-packages/pydata_sphinx_theme/layout.html", line 10, in top-level template code
    <a class='right-next' id="next-link" href="{{ next.link|e }}" title="{{ _('next page')}}">{{ next_title or next.title }}</a>
  File "/home/docs/checkouts/readthedocs.org/user_builds/abc-classroom/envs/latest/lib/python3.7/site-packages/sphinx/themes/basic/../basic/layout.html", line 169, in top-level template code
    {%- block content %}
  File "/home/docs/checkouts/readthedocs.org/user_builds/abc-classroom/envs/latest/lib/python3.7/site-packages/pydata_sphinx_theme/layout.html", line 55, in block 'content'
    {% block docs_toc %}
  File "/home/docs/checkouts/readthedocs.org/user_builds/abc-classroom/envs/latest/lib/python3.7/site-packages/pydata_sphinx_theme/layout.html", line 57, in block 'docs_toc'
    {% if not (meta is not none and 'notoc' in meta) %}
jinja2.exceptions.UndefinedError: 'meta' is undefined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/abc-classroom/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/abc-classroom/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 350, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/abc-classroom/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 294, in build_update
    len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/abc-classroom/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 359, in build
    self.finish()
  File "/home/docs/checkouts/readthedocs.org/user_builds/abc-classroom/envs/latest/lib/python3.7/site-packages/sphinx/builders/html/__init__.py", line 631, in finish
    self.finish_tasks.add_task(self.gen_indices)
  File "/home/docs/checkouts/readthedocs.org/user_builds/abc-classroom/envs/latest/lib/python3.7/site-packages/sphinx/util/parallel.py", line 49, in add_task
    res = task_func()
  File "/home/docs/checkouts/readthedocs.org/user_builds/abc-classroom/envs/latest/lib/python3.7/site-packages/sphinx/util/__init__.py", line 530, in wrapper
    return f(*args, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/abc-classroom/envs/latest/lib/python3.7/site-packages/sphinx/builders/html/__init__.py", line 647, in gen_indices
    self.write_genindex()
  File "/home/docs/checkouts/readthedocs.org/user_builds/abc-classroom/envs/latest/lib/python3.7/site-packages/sphinx/builders/html/__init__.py", line 703, in write_genindex
    self.handle_page('genindex', genindexcontext, 'genindex.html')
  File "/home/docs/checkouts/readthedocs.org/user_builds/abc-classroom/envs/latest/lib/python3.7/site-packages/sphinx/builders/html/__init__.py", line 1052, in handle_page
    (pagename, exc)) from exc
sphinx.errors.ThemeError: An error happened in rendering the page genindex.
Reason: UndefinedError("'meta' is undefined")

Theme error:
An error happened in rendering the page genindex.
Reason: UndefinedError("'meta' is undefined")
```

**Comment by kcranston** [comment]
Interesting. Where are you seeing the failures? My local build is working, and I don't see anything failing on PRs on the Actions tab.

**Comment by lwasser** [comment]
it's failing in read the docs. that error is directly from RTD! i wonder if it's a version thing --- dependency updates? So this means our docs won't update online until we fix it.  :/

**Comment by lwasser** [comment]
https://github.com/sdv-dev/SDV/issues/452

**Comment by lwasser** [comment]
i am going to close this issue as i was able to fix the docs.
