### ISSUE TITLE
Docs build failing

### ISSUE THREAD

**Issue by lwasser** [earthlab/abc-classroom#439]
just looking and noticed that the docs started failing i think [here with this update of sphinx](https://github.com/earthlab/abc-classroom/commit/ded3d6d8f05eb0490ba0933a8493af90e30c5ccf). We could try to roll back the sphinx version to see if it fixes it as this theme did used to work just fine. note it's running sphinx v4 vs v3. 

```
Running Sphinx v4.0.1
loading translations [en]... done
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 34 source files that are out of date
updating environment: [new config] 34 added, 0 changed, 0 removed
reading sources... [  2%] api
reading sources... [  5%] api/abcclassroom
reading sources... [  8%] api/abcclassroom.clone
reading sources... [ 11%] api/abcclassroom.config
reading sources... [ 14%] api/abcclassroom.distribute
reading sources... [ 17%] api/abcclassroom.feedback
reading sources... [ 20%] api/abcclassroom.github
reading sources... [ 23%] api/abcclassroom.notebook
reading sources... [ 26%] api/abcclassroom.ok
reading sources... [ 29%] api/abcclassroom.quickstart
reading sources... [ 32%] api/abcclassroom.roster
reading sources... [ 35%] api/abcclassroom.scrub_feedback
reading sources... [ 38%] api/abcclassroom.template
reading sources... [ 41%] api/abcclassroom.utils
reading sources... [ 44%] change-log
reading sources... [ 47%] collect-grade-assignments/clone
reading sources... [ 50%] collect-grade-assignments/feedback
reading sources... [ 52%] collect-grade-assignments/index
reading sources... [ 55%] collect-grade-assignments/roster
reading sources... [ 58%] contributing/code-of-conduct
reading sources... [ 61%] contributing/contributing
reading sources... [ 64%] contributing/index
reading sources... [ 67%] contributing/previous-functionality
reading sources... [ 70%] get-started/classroom-roster
reading sources... [ 73%] get-started/configuration
reading sources... [ 76%] get-started/create-course
reading sources... [ 79%] get-started/get-started
reading sources... [ 82%] get-started/index
reading sources... [ 85%] get-started/overview
reading sources... [ 88%] index
reading sources... [ 91%] manage-assignments/course-materials
reading sources... [ 94%] manage-assignments/create-grade-assignment-workflow
reading sources... [ 97%] manage-assignments/index
reading sources... [100%] manage-assignments/new_assignment

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [  2%] api
writing output... [  5%] api/abcclassroom
writing output... [  8%] api/abcclassroom.clone
writing output... [ 11%] api/abcclassroom.config
writing output... [ 14%] api/abcclassroom.distribute
writing output... [ 17%] api/abcclassroom.feedback
writing output... [ 20%] api/abcclassroom.github
writing output... [ 23%] api/abcclassroom.notebook
writing output... [ 26%] api/abcclassroom.ok
writing output... [ 29%] api/abcclassroom.quickstart
writing output... [ 32%] api/abcclassroom.roster
writing output... [ 35%] api/abcclassroom.scrub_feedback
writing output... [ 38%] api/abcclassroom.template
writing output... [ 41%] api/abcclassroom.utils
writing output... [ 44%] change-log
writing output... [ 47%] collect-grade-assignments/clone
writing output... [ 50%] collect-grade-assignments/feedback
writing output... [ 52%] collect-grade-assignments/index
writing output... [ 55%] collect-grade-assignments/roster
writing output... [ 58%] contributing/code-of-conduct
writing output... [ 61%] contributing/contributing
writing output... [ 64%] contributing/index
writing output... [ 67%] contributing/previous-functionality
writing output... [ 70%] get-started/classroom-roster
writing output... [ 73%] get-started/configuration
writing output... [ 76%] get-started/create-course
writing output... [ 79%] get-started/get-started
writing output... [ 82%] get-started/index
writing output... [ 85%] get-started/overview
writing output... [ 88%] index
writing output... [ 91%] manage-assignments/course-materials
writing output... [ 94%] manage-assignments/create-grade-assignment-workflow
writing output... [ 97%] manage-assignments/index
writing output... [100%] manage-assignments/new_assignment

generating indices... genindex failed

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/abc-classroom/envs/latest/lib/python3.7/site-packages/sphinx/builders/html/__init__.py", line 1044, in handle_page
    output = self.templates.render(templatename, ctx)
  File "/home/docs/checkouts/readthedocs.org/user_builds/abc-classroom/envs/latest/lib/python3.7/site-packages/readthedocs_ext/readthedocs.py", line 185, in rtd_render
    content = old_render(template, render_context)
  File "/home/docs/checkouts/readthedocs.org/user_builds/abc-classroom/envs/latest/lib/python3.7/site-packages/sphinx/jinja2glue.py", line 191, in render
    return self.environment.get_template(template).render(context)
  File "/home/docs/checkouts/readthedocs.org/user_builds/abc-classroom/envs/latest/lib/python3.7/site-packages/jinja2/environment.py", line 1289, in render
    self.environment.handle_exception()
  File "/home/docs/checkouts/readthedocs.org/user_builds/abc-classroom/envs/latest/lib/python3.7/site-packages/jinja2/environment.py", line 924, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/docs/checkouts/readthedocs.org/user_builds/abc-classroom/envs/latest/lib/python3.7/site-packages/sphinx/themes/basic/genindex.html", line 28, in top-level template code
    {{ firstname|e }}
  File "/home/docs/checkouts/readthedocs.org/user_builds/abc-classroom/envs/latest/lib/python3.7/site-packages/pydata_sphinx_theme/layout.html", line 10, in top-level template code
    <a class='right-next' id="next-link" href="{{ next.link|e }}" title="{{ _('next page')}}">{{ next_title or next.title }}</a>
  File "/home/docs/checkouts/readthedocs.org/user_builds/abc-classroom/envs/latest/lib/python3.7/site-packages/sphinx/themes/basic/../basic/layout.html", line 169, in top-level template code
    {%- block content %}
  File "/home/docs/checkouts/readthedocs.org/user_builds/abc-classroom/envs/latest/lib/python3.7/site-packages/pydata_sphinx_theme/layout.html", line 55, in block 'content'
    {% block docs_toc %}
  File "/home/docs/checkouts/readthedocs.org/user_builds/abc-classroom/envs/latest/lib/python3.7/site-packages/pydata_sphinx_theme/layout.html", line 57, in block 'docs_toc'
    {% if not (meta is not none and 'notoc' in meta) %}
jinja2.exceptions.UndefinedError: 'meta' is undefined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/abc-classroom/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/abc-classroom/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 350, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/abc-classroom/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 294, in build_update
    len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/abc-classroom/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 359, in build
    self.finish()
  File "/home/docs/checkouts/readthedocs.org/user_builds/abc-classroom/envs/latest/lib/python3.7/site-packages/sphinx/builders/html/__init__.py", line 631, in finish
    self.finish_tasks.add_task(self.gen_indices)
  File "/home/docs/checkouts/readthedocs.org/user_builds/abc-classroom/envs/latest/lib/python3.7/site-packages/sphinx/util/parallel.py", line 49, in add_task
    res = task_func()
  File "/home/docs/checkouts/readthedocs.org/user_builds/abc-classroom/envs/latest/lib/python3.7/site-packages/sphinx/util/__init__.py", line 530, in wrapper
    return f(*args, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/abc-classroom/envs/latest/lib/python3.7/site-packages/sphinx/builders/html/__init__.py", line 647, in gen_indices
    self.write_genindex()
  File "/home/docs/checkouts/readthedocs.org/user_builds/abc-classroom/envs/latest/lib/python3.7/site-packages/sphinx/builders/html/__init__.py", line 703, in write_genindex
    self.handle_page('genindex', genindexcontext, 'genindex.html')
  File "/home/docs/checkouts/readthedocs.org/user_builds/abc-classroom/envs/latest/lib/python3.7/site-packages/sphinx/builders/html/__init__.py", line 1052, in handle_page
    (pagename, exc)) from exc
sphinx.errors.ThemeError: An error happened in rendering the page genindex.
Reason: UndefinedError("'meta' is undefined")

Theme error:
An error happened in rendering the page genindex.
Reason: UndefinedError("'meta' is undefined")
```

**Comment by lwasser** [comment]
fixed!! closing this
